---
- hosts: all
  become: yes
  gather_facts: False
  pre_tasks:
    - raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
    - setup:

  roles:
    #- mongrelion.docker
    - franela.pwd